name: test_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  json_annotation: ^4.9.0
  orm: ^5.3.4
  crypto: ^3.0.7
  dart_frog_auth: ^1.2.2
  dart_jsonwebtoken: ^3.3.1

dev_dependencies:
  build_runner: ^2.10.1
  json_serializable: ^6.9.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
